package com.aws.task.domain.enitiy;

import java.time.Instant;
import java.time.LocalDate;
import java.util.Objects;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GenerationType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity  //annotation to mark this class as a JPA entity (into the database)
@Table(name = "tasks") //annotation to specify the table name in the database (tasks)
public class Task {

    @Id //annotation to mark this field as the primary key of the entity
    @GeneratedValue(strategy = GenerationType.UUID) //annotation to specify that the value of this field should be generated automatically (UUID)
    @Column(name = "id", updatable = false, nullable = false) //annotation to specify the column name in the database and constraints (not updatable, not nullable)
    private UUID id; // Unique identifier for the task

    @Column(name = "title", nullable = false) //annotation to specify the column name in the database and constraints (not nullable)
    private String title; // Title of the task

    @Column(name = "description", length = 1000) //annotation to specify the column name in the database and constraints (length 1000)
    private String description; // Description of the task

    @Column(name = "due_date") //annotation to specify the column name in the database
    private LocalDate dueDate; // Due date of the task
    
    @Enumerated(EnumType.STRING) //annotation to specify that this field is an enum and should be stored as a string in the database
    @Column(name = "status", nullable = false) //annotation to specify the column name in the database and constraints (not nullable)
    private TaskStatus status; // Status of the task (OPEN, COMPLETE)

    @Enumerated(EnumType.STRING) //annotation to specify that this field is an enum and should be stored as a string in the database
    @Column(name = "priority", nullable = false) //annotation to specify the column name in the database and constraints (not nullable)
    private TaskPriority priority; // Priority of the task (HIGH, MEDIUM, LOW)

    @Column(name = "created", nullable = false, updatable = false) //annotation to specify the column name in the database and constraints (not nullable, not updatable)
    private Instant created; // Timestamp for when the task was created

    @Column(name = "updated", nullable = false) //annotation to specify the column name in the database and constraints (not nullable)
    private Instant updated; // Timestamp for when the task was last updated


    // Getters and setters for all fields
    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public LocalDate getDueDate() {
        return dueDate;
    }

    public void setDueDate(LocalDate dueDate) {
        this.dueDate = dueDate;
    }

    public TaskStatus getStatus() {
        return status;
    }

    public void setStatus(TaskStatus status) {
        this.status = status;
    }

    public TaskPriority getPriority() {
        return priority;
    }

    public void setPriority(TaskPriority priority) {
        this.priority = priority;
    }

    public Instant getCreated() {
        return created;
    }

    public void setCreated(Instant created) {
        this.created = created;
    }

    public Instant getUpdated() {
        return updated;
    }

    public void setUpdated(Instant updated) {
        this.updated = updated;
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        Task task = (Task) o;
        return Objects.equals(id, task.id);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }

    @Override
    public String toString() {
        return "Task [id=" + id + ", title=" + title + ", description=" + description + ", dueDate=" + dueDate
                + ", status=" + status + ", priority=" + priority + ", created=" + created + ", updated=" + updated
                + "]";
    }

    // Auto generated hashCode and equals methods based on the id field , they are different from the ones generated by IntelliJ IDEA, I've commented them just fore future reference.
    //I copyied the implementation from the video, above. 
    /**
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Task other = (Task) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        } else if (!id.equals(other.id))
            return false;
        return true;
    }
    **/
}
