package com.aws.task.service.impl;

import java.time.Instant;

import org.springframework.stereotype.Service;

import com.aws.task.domain.CreateTaskRequest;
import com.aws.task.domain.enitiy.Task;
import com.aws.task.domain.enitiy.TaskStatus;
import com.aws.task.repository.TaskRepository;
import com.aws.task.service.TaskService;

@Service
public class TaskServiceImpl implements TaskService {

private final TaskRepository taskRepository;

    public TaskServiceImpl(TaskRepository taskRepository) {
        this.taskRepository = taskRepository;
    }

    @Override
    public Task createTask(CreateTaskRequest request) {
        Instant now = Instant.now();
        
        Task task = new Task(
            null, // ID will be generated by the database
            request.title(),
            request.description(),
            request.dueDate(),
            TaskStatus.OPEN,
            request.priority(),
            now,
            now
        );
        return taskRepository.save(task);
    }

}
