package com.aws.task.service.impl;

import java.time.Instant;
import java.util.List;

import org.springframework.data.domain.Sort;
import org.springframework.data.domain.Sort.Direction;
import org.springframework.stereotype.Service;

import com.aws.task.domain.CreateTaskRequest;
import com.aws.task.domain.entity.Task;
import com.aws.task.domain.entity.TaskStatus;
import com.aws.task.repository.TaskRepository;
import com.aws.task.service.TaskService;

@Service
public class TaskServiceImpl implements TaskService {

private final TaskRepository taskRepository;

    public TaskServiceImpl(TaskRepository taskRepository) {
        this.taskRepository = taskRepository;
    }

    @Override
    public Task createTask(CreateTaskRequest request) {
        Instant now = Instant.now();
        
        Task task = new Task(
            null, // ID will be generated by the database
            request.title(),
            request.description(),
            request.dueDate(),
            TaskStatus.OPEN,
            request.priority(),
            now,
            now
        );
        return taskRepository.save(task);
    }

    @Override
    public List<Task> listTasks() {
        return taskRepository.findAll(Sort.by(Direction.ASC, "created"));
    }

}
